"""rename suggested analyses to suggested analysis

Revision ID: 02838e93c92e
Revises: 818aa440fbf0
Create Date: 2026-04-03 11:29:19.464640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02838e93c92e'
down_revision: Union[str, Sequence[str], None] = '818aa440fbf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_profiles', sa.Column('suggested_analysis', sa.JSON(), nullable=True))
    op.drop_column('dataset_profiles', 'suggested_analyses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_profiles', sa.Column('suggested_analyses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('dataset_profiles', 'suggested_analysis')
    # ### end Alembic commands ###
